@startuml
!include Styles.puml

box console COLOR_CONSOLE_SEGMENT
participant ":InputParser" as InputParser COLOR_CONSOLE
participant "<<Class>>\nAddInstrumentParser" as AddInstrumentParser COLOR_CONSOLE
participant ":AddStockParser" as AddStockParser COLOR_CONSOLE
participant ":AddStockCommand" as AddStockCommand COLOR_COMMANDS
end box

box commands COLOR_FAINT_GREEN
participant ":AddStockCommand" as AddStockCommand COLOR_FAINT_GREEN
end box

box ui COLOR_LIGHT_BLUE
participant ":TextUi" as TextUi COLOR_UI
end box


[-> InputParser : filterByCommandType({"add"}, instruments)
activate InputParser

InputParser -> InputParser : getAddInstrumentParameters()
activate InputParser

InputParser -> TextUi : displayAddInstrumentFirstInstruction()
activate TextUi

TextUi --> InputParser
deactivate TextUi

InputParser -> AddInstrumentParser : filterByInstrumentType({"stock"})
activate AddInstrumentParser

note right
The parameter "stock" was
given by the user after
displayAddInstrumentFirstInstruction().
end note

create AddStockParser
AddInstrumentParser -> AddStockParser : AddStockParser()
activate AddStockParser

AddStockParser --> AddInstrumentParser
deactivate AddStockParser

AddInstrumentParser -> AddStockParser : initParameters()
activate AddStockParser
AddStockParser --> AddInstrumentParser
deactivate AddStockParser

ref over AddInstrumentParser, AddStockParser, AddStockCommand
Get stock details from user and create the AddStockCommand
endref

AddInstrumentParser --> InputParser : return command
deactivate AddInstrumentParser
deactivate InputParser
[<-- InputParser : return command
deactivate InputParser

@enduml
