@startuml
!include Styles.puml

group sd Get stock details from user and create the AddStockCommand
participant ":AddStockParser" as AddStockParser COLOR_CONSOLE
participant ":AddStockCommand" as AddStockCommand COLOR_COMMANDS

[-> AddStockParser : getInstrumentParameters()
activate AddStockParser
[<--AddStockParser : getGeneralParameters("stock")

[--> AddStockParser

note right
Both getGeneralParameters() and
getStockSpecificParameters()
would prompt the user to input details for every
attribute to store as parameters.
end note

AddStockParser -> AddStockParser : getStockSpecificParameters()
activate AddStockParser
AddStockParser --> AddStockParser
deactivate AddStockParser

create AddStockCommand
AddStockParser -> AddStockCommand : AddStockCommand()
activate AddStockCommand
AddStockCommand --> AddStockParser
deactivate AddStockCommand

[<--AddStockParser : return command
deactivate AddStockParser

[->AddStockParser : getParameters()
activate AddStockParser
[<--AddStockParser : return parameters
deactivate AddStockParser

[-> AddStockCommand : setParams(parameters)
activate AddStockCommand
[<--AddStockCommand
deactivate AddStockCommand

end
@enduml