@startuml
!include Styles.puml

group sd Get stock details from user and create the AddStockCommand

box console COLOR_CONSOLE_SEGMENT
participant "<<class>>\nAddInstrumentParser" as AddInstrumentParser COLOR_CONSOLE
participant ":AddStockParser" as AddStockParser COLOR_CONSOLE
participant "<<class>>\nAddStockParser" as ClassAddStockParser COLOR_CONSOLE
end box

box command COLOR_FAINT_GREEN
participant ":AddStockCommand" as AddStockCommand COLOR_COMMANDS
end box
activate AddInstrumentParser

AddInstrumentParser-> AddStockParser : getInstrumentParameters()
activate AddStockParser
AddStockParser->ClassAddStockParser : getGeneralParameters("stock")
activate ClassAddStockParser
ClassAddStockParser--> AddStockParser
deactivate ClassAddStockParser


note right
Both getGeneralParameters() and
getStockSpecificParameters()
would prompt the user to input details for every
attribute to store as parameters.
end note

AddStockParser -> AddStockParser : getStockSpecificParameters()
activate AddStockParser
AddStockParser --> AddStockParser
deactivate AddStockParser

create AddStockCommand
AddStockParser -> AddStockCommand : AddStockCommand()
activate AddStockCommand
AddStockCommand --> AddStockParser
deactivate AddStockCommand

AddInstrumentParser<--AddStockParser : return command
deactivate AddStockParser

AddInstrumentParser->AddStockParser : getParameters()
activate AddStockParser
AddInstrumentParser<--AddStockParser : return parameters
deactivate AddStockParser

AddInstrumentParser-> AddStockCommand : setParams(parameters)
activate AddStockCommand
AddInstrumentParser<--AddStockCommand
deactivate AddStockCommand

end
@enduml
