!define COLOR_WHITE #FFFFFF
!define COLOR_SILVER #C0C0C0
!define COLOR_GREY #A5A8AC
!define COLOR_BLACK #000000
!define COLOR_BROWN #800000
!define COLOR_RED #FF0000
!define COLOR_YELLOW #FFFF00
!define COLOR_BRIGHT_GREEN #00FF00
!define COLOR_DARK_GREEN #008000
!define COLOR_LIGHT_BLUE #00FFFF
!define COLOR_TEAL #008080
!define COLOR_DARK_BLUE #0000FF
!define COLOR_PINK #FF00FF
!define COLOR_PURPLE #800080
!define COLOR_FAINT_TEAL #BBF1F1
!define COLOR_FAINT_GREEN #C2F5CC
!define COLOR_LIGHT_PURPLE #CBC3E3