@startuml
!include Styles.puml

Package "Commands                    "  <<Rectangle>>{
     Class "{abstract}\nCommand" as Command COLOR_COMMANDS {
     {method} + setData
     {method} + setParams
     {method} + execute: String
     }
     Class ViewCommand COLOR_COMMANDS
     Class EditInstrumentCommand COLOR_COMMANDS
     Class DoneCommand COLOR_COMMANDS
     Class DeleteCommand COLOR_COMMANDS

     Class InvalidCommand COLOR_COMMANDS
     Class ABCCommand COLOR_COMMANDS
     Class AddInstrumentCommand COLOR_COMMANDS
     Class "{abstract}\nIndexedCommand" as IndexedCommand COLOR_COMMANDS

     Class AddXYZCommand COLOR_COMMANDS
}


Class InstrumentManager COLOR_MODEL {
    {method} + getSize: int
    {method} + getInstruments: ArrayList<Instrument>
    {method} + getInstrument: Instrument
    {method} + addInstrument: Instrument
    {method} + findInstruments: ArrayList<Instrument>
    {method} + deleteInstrument
    {method} + editInstrument
}

Class TextUi COLOR_UI

show Command members
show InstrumentManager members

Command -up[COLOR_COMMANDS]->"1" InstrumentManager
InvalidCommand -[COLOR_COMMANDS]-|>Command
ABCCommand -[COLOR_COMMANDS]-|>Command
AddInstrumentCommand -[COLOR_COMMANDS]-|>Command
IndexedCommand -up[COLOR_COMMANDS]-|>Command

AddXYZCommand -[COLOR_COMMANDS]-|>AddInstrumentCommand

EditInstrumentCommand -[COLOR_COMMANDS]-|>IndexedCommand
ViewCommand -[COLOR_COMMANDS]-|>IndexedCommand
DoneCommand -[COLOR_COMMANDS]-|>IndexedCommand
DeleteCommand -[COLOR_COMMANDS]-|>IndexedCommand

AddXYZCommand -[COLOR_COMMANDS].>TextUi
ABCCommand -[COLOR_COMMANDS].>TextUi
DeleteCommand -[COLOR_COMMANDS].>TextUi
DoneCommand -[COLOR_COMMANDS].>TextUi
EditInstrumentCommand -[COLOR_COMMANDS].>TextUi
ViewCommand -[COLOR_COMMANDS].>TextUi

@enduml
