@startuml
'https://plantuml.com/class-diagram
!include Styles.puml

box console COLOR_CONSOLE_SEGMENT
participant ":InputParser" as InputParser COLOR_CONSOLE
participant ":EditInstrumentParser" as EditInstrumentParser COLOR_MODEL
end box

box command COLOR_FAINT_GREEN
participant ":EditInstrumentCommand" as EditInstrumentCommand COLOR_COMMANDS
end box

[-> InputParser : filterByCommandType({"edit", "1"},\n instruments)
activate InputParser

InputParser -> InputParser: getEditInstrumentCommand({"edit", "1"},\n instruments)
activate InputParser

InputParser -> InputParser: getAndValidateIndexNumber({"edit", "1"}, instrument)

activate InputParser
InputParser --> InputParser
deactivate InputParser

InputParser -> InputParser: get parameters from user and check if parameter entered is valid parameters
activate InputParser
InputParser --> InputParser
deactivate InputParser


create EditInstrumentParser
InputParser -> EditInstrumentParser: EditInstrumentParser()
activate EditInstrumentParser
EditInstrumentParser --> InputParser
deactivate EditInstrumentParser

InputParser -> EditInstrumentParser: createEditCommand({"name"}, instrument, 1);
activate EditInstrumentParser

ref over EditInstrumentParser
check if parameter is entered and add to HashMap
endref

create EditInstrumentCommand
EditInstrumentParser -> EditInstrumentCommand: EditInstrumentCommand()
activate EditInstrumentCommand
EditInstrumentCommand --> EditInstrumentParser
deactivate EditInstrumentCommand

EditInstrumentParser -> EditInstrumentCommand: setIndex()
activate EditInstrumentCommand
EditInstrumentCommand --> EditInstrumentParser
deactivate EditInstrumentCommand

EditInstrumentParser --> InputParser: return editInstrumentCommand
deactivate EditInstrumentParser

InputParser --> InputParser: return editInstrumentCommand
deactivate InputParser
[<--InputParser: return editInstrumentCommand
deactivate InputParser

@enduml