@startuml
'https://plantuml.com/sequence-diagram
!include Styles.puml

participant ":EditInstrumentParser" as EditInstrumentParser COLOR_COMMANDS
group sd check if parameter is entered and \n add to HashMap

[-> EditInstrumentParser: getParametersToEdit({"name"}, instrument, 1);
activate EditInstrumentParser

EditInstrumentParser -> EditInstrumentParser: getEditedParameters({"name"}, instrument)
activate EditInstrumentParser

loop valid name is entered
EditInstrumentParser -> EditInstrumentParser: editNameParameter("stock", {"name"})
activate EditInstrumentParser
EditInstrumentParser --> EditInstrumentParser
deactivate EditInstrumentParser
end

loop valid parameter is entered
EditInstrumentParser -> EditInstrumentParser: editXYZParameter({"name"})
activate EditInstrumentParser
EditInstrumentParser --> EditInstrumentParser
deactivate EditInstrumentParser
end

EditInstrumentParser --> EditInstrumentParser
deactivate EditInstrumentParser
EditInstrumentParser -->[
deactivate EditInstrumentParser

end
@enduml