@startuml
'https://plantuml.com/sequence-diagram
!include Styles.puml

participant ":EditInstrumentParser" as EditInstrumentParser COLOR_COMMANDS
group sd check if parameter is entered and \n add to HashMap

[-> EditInstrumentParser: getParametersToEdit({"name"}, instrument, 1);
activate EditInstrumentParser

EditInstrumentParser -> EditInstrumentParser: getEditedParameters({"name"}, instrument)
activate EditInstrumentParser

loop valid name is entered
EditInstrumentParser -> EditInstrumentParser: editNameParameter("stock", {"name"})
note left: This method check if the parameter is entered \nthen prompts user to input new value of the parameter.\nMethod loop until a valid value is input.
activate EditInstrumentParser
EditInstrumentParser --> EditInstrumentParser
deactivate EditInstrumentParser
end

loop valid parameter is entered
EditInstrumentParser -> EditInstrumentParser: editXYZParameter({"name"})
note left: This box represents methods that does the same\nas the one above but for all other parameters.
activate EditInstrumentParser
EditInstrumentParser --> EditInstrumentParser
deactivate EditInstrumentParser
end

EditInstrumentParser --> EditInstrumentParser
deactivate EditInstrumentParser
EditInstrumentParser -->[
deactivate EditInstrumentParser

end
@enduml