@startuml
'https://plantuml.com/sequence-diagram
!include Styles.puml

participant ":InputParser" as InputParser COLOR_MODEL
group sd get parameters from user and check if parameter entered is valid parameters

activate InputParser
InputParser -> InputParser: getParametersToEdit({"name", "current-price",\n "sentiment", "returns", "remark"})
InputParser -> InputParser: getUserInput()
activate InputParser
InputParser --> InputParser: return user input of "name"
deactivate InputParser
InputParser -> InputParser: getCommandComponents("name")
activate InputParser
InputParser --> InputParser: return user input split by spaces
deactivate InputParser
InputParser -> InputParser: filterInvalidParameters("name",\n {"name", "current-price", "sentiment", "returns", "remark"})
activate InputParser
InputParser --> InputParser: return HashSet containing valid parameters
deactivate InputParser

end
@enduml