@startuml
!include Styles.puml
'https://plantuml.com/class-diagram

Package "filemanager"  <<Rectangle>>{
     Class Storage COLOR_STORAGE
     Class InstrumentDecoder COLOR_STORAGE
     Class InstrumentEncoder COLOR_STORAGE
     Class XYZDecoder COLOR_STORAGE
}

Class outside COLOR_WHITE
outside -down[COLOR_STORAGE]-> Storage
XYZDecoder -up[COLOR_STORAGE].|>InstrumentDecoder
Storage -left[COLOR_STORAGE].> InstrumentEncoder
Storage -right[COLOR_STORAGE].> InstrumentDecoder

note bottom of XYZDecoder: XYZDecoder = CryptoDecoder, ForexDecoder, \nEtfDecoder, StockDEcoder

@enduml
