@startuml
!include Styles.puml

'https://plantuml.com/sequence-diagram
box filemanager COLOR_STORAGE_SEGMENT
participant ":Storage" as Storage COLOR_STORAGE
participant ":InstrumentEncoder" as InstrumentEncoder COLOR_STORAGE
end box

box model COLOR_MODEL_SEGMENT
participant ":Instrument" as Instrument COLOR_MODEL
end box

[-> Storage: updateFileData(instruments)
activate Storage

Storage-> Storage: writeFileData(instruments)
activate Storage

note bottom
writeFileData initialises a new
FileWriter to write into the txt file
and calls the writeFile method in
InstrumentEncoder
end note

Storage-> InstrumentEncoder: writeFile(instruments, writeToFile)
activate InstrumentEncoder

note right
writeToFile is of type FileWriter
to enable a FileWriter to write to
the text file
end note

loop each instrument
    InstrumentEncoder-> Instrument: textFileFormatting()
    activate Instrument
    Instrument--> InstrumentEncoder: return InstrumentInFileFormat
    deactivate Instrument
    note bottom
    InstrumentInFileFormat
    is of type String eg.
    {"Stock;AAPL;32.0;
    positive;false;Nil"}
    end note

    InstrumentEncoder-> InstrumentEncoder: editFile(InstrumentInFileFormat, writeToFile)
    activate InstrumentEncoder
    InstrumentEncoder--> InstrumentEncoder
    deactivate InstrumentEncoder

    note right
    editFile writes to the txt file with
    the formatted instrument
    end note

end
InstrumentEncoder--> Storage
deactivate InstrumentEncoder

Storage--> Storage
deactivate Storage

[<-- Storage
deactivate Storage

@enduml
