@startuml
!include Styles.puml

Package "Model                    "  <<Rectangle>>{
     Class "{abstract}\nInstrument" as Instrument COLOR_MODEL
     Class InstrumentManager COLOR_MODEL {
        <color:WHITE>+ addInstrument(Instrument)</color>
        <color:WHITE>+ findInstruments(String): ArrayList<Instrument></color>
        <color:WHITE>+ deleteInstrument(int)</color>
        <color:WHITE>+ editInstrument(int, HashMap<String, String>)</color>
     }
     Class Crypto COLOR_MODEL
     Class Stock COLOR_MODEL
     Class Etf COLOR_MODEL
     Class Forex COLOR_MODEL
}

show InstrumentManager members

Class main COLOR_MAIN
main -down[COLOR_MODEL]->"1" InstrumentManager
Crypto -up[COLOR_MODEL]-|>Instrument
Stock -up[COLOR_MODEL]-|>Instrument
Etf -up[COLOR_MODEL]-|>Instrument
Forex -up[COLOR_MODEL]-|>Instrument
InstrumentManager -down[COLOR_MODEL]-> "              *" Instrument

@enduml
