@startuml
'https://plantuml.com/sequence-diagram
!include Styles.puml

box ui COLOR_LIGHT_BLUE
participant ":TextUi" as TextUi COLOR_UI
end box

box model COLOR_MODEL_SEGMENT
participant ":Instrument" as Instrument COLOR_MODEL
end box

[-> TextUi : displayAllInstruments(instruments)
activate TextUi

TextUi -> TextUi : displayInstruments()
activate TextUi

    loop each instrument
        TextUi -> TextUi : constructLineInList(idx, instrument)
        activate TextUi

        TextUi -> Instrument : getGeneralParams()
        activate Instrument

        Instrument --> TextUi

        TextUi --> TextUi : printout instrument's \ngeneral parameters
        deactivate Instrument

        note bottom
        The getGeneralParams() method
        returns the instrument's name, current price,
        and sentiment as String.
        end note

        deactivate TextUi
end

deactivate TextUi


@enduml